// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using School_Knowledge_Systems.Server.Data;

#nullable disable

namespace School_Knowledge_Systems.Server.Migrations
{
    [DbContext(typeof(SKSDbContext))]
    [Migration("20231207170344_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("School_Knowledge_Systems.Server.Models.Level", b =>
                {
                    b.Property<string>("ClassID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AssignedStudents")
                        .HasColumnType("int");

                    b.Property<int>("UnAssignedStudents")
                        .HasColumnType("int");

                    b.HasKey("ClassID");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("School_Knowledge_Systems.Server.Models.Section", b =>
                {
                    b.Property<string>("SectionID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClassID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NoOfClassesPerWeek")
                        .HasColumnType("int");

                    b.Property<int>("StudentCount")
                        .HasColumnType("int");

                    b.HasKey("SectionID");

                    b.HasIndex("ClassID");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("School_Knowledge_Systems.Server.Models.SectionSubject", b =>
                {
                    b.Property<string>("SubjectID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SectionID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SubjectID", "SectionID");

                    b.HasIndex("SectionID");

                    b.ToTable("SectionSubjects");
                });

            modelBuilder.Entity("School_Knowledge_Systems.Server.Models.Student", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClassID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("FatherPhoneNumber")
                        .HasColumnType("int");

                    b.Property<string>("SectionID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.HasIndex("ClassID");

                    b.HasIndex("SectionID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("School_Knowledge_Systems.Server.Models.Subject", b =>
                {
                    b.Property<string>("SubjectID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClassID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NoOfClassesPerWeek")
                        .HasColumnType("int");

                    b.Property<int>("TeacherID")
                        .HasColumnType("int");

                    b.HasKey("SubjectID");

                    b.HasIndex("ClassID");

                    b.HasIndex("TeacherID");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("School_Knowledge_Systems.Server.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherID"));

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<int>("TeacherClassesPerWeek")
                        .HasColumnType("int");

                    b.Property<string>("TeacherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeacherID");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("School_Knowledge_Systems.Server.Models.Section", b =>
                {
                    b.HasOne("School_Knowledge_Systems.Server.Models.Level", "Class")
                        .WithMany("Sections")
                        .HasForeignKey("ClassID");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("School_Knowledge_Systems.Server.Models.SectionSubject", b =>
                {
                    b.HasOne("School_Knowledge_Systems.Server.Models.Section", "Section")
                        .WithMany("Subjects")
                        .HasForeignKey("SectionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School_Knowledge_Systems.Server.Models.Subject", "Subject")
                        .WithMany("Sections")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("School_Knowledge_Systems.Server.Models.Student", b =>
                {
                    b.HasOne("School_Knowledge_Systems.Server.Models.Level", "Class")
                        .WithMany()
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School_Knowledge_Systems.Server.Models.Section", "Section")
                        .WithMany("Students")
                        .HasForeignKey("SectionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("School_Knowledge_Systems.Server.Models.Subject", b =>
                {
                    b.HasOne("School_Knowledge_Systems.Server.Models.Level", "Class")
                        .WithMany()
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School_Knowledge_Systems.Server.Models.Teacher", "Teacher")
                        .WithMany("TaughtSubjects")
                        .HasForeignKey("TeacherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("School_Knowledge_Systems.Server.Models.Level", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("School_Knowledge_Systems.Server.Models.Section", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("School_Knowledge_Systems.Server.Models.Subject", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("School_Knowledge_Systems.Server.Models.Teacher", b =>
                {
                    b.Navigation("TaughtSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
